---
title: Annapurna Chitta
logo: assets/img/headshot 1.jpg
description: 6+ years in data-driven decision-making, optimizing people
  strategies, driving insights, process improvements, and growth.
theme: jekyll-theme-minimal
