title: Annapurna Chitta
logo: assets/img/headshot 1.jpg
description:  6+ years of experience in data-driven decision-making. Committed to leveraging analytics to enhance business performance, optimize organizational people strategies, and support sustainable growth. Skilled in 
transforming complex data into actionable insights that drive process improvements and foster a culture of continuous 
learning.
show_downloads: true
theme: jekyll-theme-minimal
