---
title: Annapurna Chitta 
        (Anu Chitta)
logo: assets/img/headshot 1.jpg
description:Data-driven decision-making, optimizing people
  strategies, driving insights, process improvements and growth.
theme: jekyll-theme-minimal
social_links:
  - name: LinkedIn
    url: "https://www.linkedin.com/in/annapurna-chitta"
    icon: "https://cdn-icons-png.flaticon.com/512/174/174857.png"  # LinkedIn icon
  - name: Email
    url: "chittaa@duq.edu"
    icon: "https://cdn-icons-png.flaticon.com/512/732/732200.png"  # Email icon
