title: Annapurna Chitta
logo: WhatsApp Image 2025-02-04 at 4.03.05 PM.jpeg
description: Seeking an Analytics role to leverage data insights for better business decisions and drive organizational performance improvements
theme: jekyll-theme-minimal
