title: Annapurna Chitta
logo:C:\Anu 
description: Seeking an Analytics role to leverage data insights for better business decisions and drive organizational performance improvements
theme: jekyll-theme-minimal
